import type { VocabItem } from '../types/vocabulary'
import { generateVocabId } from '../lib/vocab-id'

const BOOK_SOURCE = 'minna_shokyuu_1'
const PREFIX = 'mnn1'

export const sampleVocabulary: VocabItem[] = [
  {
    vocab_id: generateVocabId(PREFIX, BOOK_SOURCE, 1, null, 'わたし'),
    word: null,
    reading: 'わたし',
    romaji: 'watashi',
    meaning_en: 'I',
    meaning_vi: '1. N. Tôi',
    pitch_pattern: null,
    pitch_type: null,
    audio_filename: null,
    pos: [],
    jlpt_level: 5,
    book_source: BOOK_SOURCE,
    lesson_number: 1,
    examples: [],
    tags: [],
    deprecated: false,
  },
  {
    vocab_id: generateVocabId(PREFIX, BOOK_SOURCE, 1, null, 'あなた'),
    word: null,
    reading: 'あなた',
    romaji: 'anata',
    meaning_en: 'you',
    meaning_vi: '2. N. Bạn, anh, chị, em',
    pitch_pattern: null,
    pitch_type: null,
    audio_filename: null,
    pos: [],
    jlpt_level: 5,
    book_source: BOOK_SOURCE,
    lesson_number: 1,
    examples: [],
    tags: [],
    deprecated: false,
  },
  {
    vocab_id: generateVocabId(PREFIX, BOOK_SOURCE, 2, '行きます', 'いきます'),
    word: '行きます',
    reading: 'いきます',
    romaji: 'ikimasu',
    meaning_en: 'to go',
    meaning_vi: '1. V. Đi',
    pitch_pattern: null,
    pitch_type: null,
    audio_filename: null,
    pos: [],
    jlpt_level: 5,
    book_source: BOOK_SOURCE,
    lesson_number: 2,
    examples: [],
    tags: [],
    deprecated: false,
  },
  {
    vocab_id: generateVocabId(PREFIX, BOOK_SOURCE, 2, '来ます', 'きます'),
    word: '来ます',
    reading: 'きます',
    romaji: 'kimasu',
    meaning_en: 'to come',
    meaning_vi: '2. V. Đến',
    pitch_pattern: null,
    pitch_type: null,
    audio_filename: null,
    pos: [],
    jlpt_level: 5,
    book_source: BOOK_SOURCE,
    lesson_number: 2,
    examples: [],
    tags: [],
    deprecated: false,
  },
  {
    vocab_id: generateVocabId(PREFIX, BOOK_SOURCE, 3, '食べます', 'たべます'),
    word: '食べます',
    reading: 'たべます',
    romaji: 'tabemasu',
    meaning_en: 'to eat',
    meaning_vi: '1. V. Ăn',
    pitch_pattern: null,
    pitch_type: null,
    audio_filename: null,
    pos: [],
    jlpt_level: 5,
    book_source: BOOK_SOURCE,
    lesson_number: 3,
    examples: [],
    tags: [],
    deprecated: false,
  },
]
